import type { Metadata } from 'next';
import { JetBrains_Mono } from 'next/font/google';
import { Outfit } from 'next/font/google';
import './globals.css';
import React from 'react';
import Header from '@/components/Header';

const jetBrains = JetBrains_Mono({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-jetBrains', // optionnel (utile avec Tailwind)
});

const outfit = Outfit({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-outfit', // optionnel (utile avec Tailwind)
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} ${jetBrains.variable} h-full antialiased`}
    >
      <body className={`flex min-h-full flex-col`}>{children}</body>
    </html>
  );
}
